#!/usr/bin/env bash
# Modified versions of a script found in the Primagen's dots
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find -L ~/ ~/Projects ~/Projects/Plugins ~/.config -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

numeric_sessions=$(tmux list-sessions | awk -F : '{print $1}' | grep -E '[0-9]')

for x in $numeric_sessions
do
    tmux kill-session -t $x
done
