"$schema" = 'https://starship.rs/config-schema.json'

format = """
$all
${custom.date}$os$shell$character
"""

add_newline = false
palette = 'tokyonight'

[palettes.tokyonight]
green = '#73daca'
red = '#f7768e'
black = '#414868'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

[username]
show_always = true
format = '[$user@]($style)'
style_user = 'magenta'

[hostname]
ssh_only = false
style = 'magenta'

[directory]
truncation_length = 8
truncation_symbol = ".../"
style = 'cyan'

[shell]
disabled = false
fish_indicator = "[󰈺](green)" # Use nerd font symbols
bash_indicator = "[](green)"
zsh_indicator = "[󰞷](green)"

[os]
disabled = false

symbols.Arch = "[󰣇](blue) "
symbols.EndeavourOS = "[󰣇](blue) "

[line_break]
disabled = true

[character]
error_symbol = '[✗](bold red) '

[fill]
symbol = " "

[custom.date]
command = 'date +%a" "%b" "%d" "%H:%M:%S'
when = true
style = 'magenta'
